version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - db-data:/Users/luongtankhang/Desktop/PTUDW/docker-env/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: visioner
      PGDATA: /Users/luongtankhang/Desktop/PTUDW/docker-env/db
  redis:
    image: 'bitnami/redis:4.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "mqadmin"
      RABBITMQ_DEFAULT_PASS: "mqadmin"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - "rabbit_data:/var/lib/rabbitmq"


volumes:
  db-data:
    driver: local
  redis_data:
    driver: local
  rabbit_data:
    driver: local
